//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1022
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCguess.Serv {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Serv.HelloGustaSoap")]
    public interface HelloGustaSoap {
        
        // CODEGEN: Generating message contract since element name email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerificaLogin", ReplyAction="*")]
        WCguess.Serv.VerificaLoginResponse VerificaLogin(WCguess.Serv.VerificaLoginRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FacebookLogin", ReplyAction="*")]
        WCguess.Serv.FacebookLoginResponse FacebookLogin(WCguess.Serv.FacebookLoginRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CadastraLogin", ReplyAction="*")]
        WCguess.Serv.CadastraLoginResponse CadastraLogin(WCguess.Serv.CadastraLoginRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllRanksResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllRanks", ReplyAction="*")]
        WCguess.Serv.GetAllRanksResponse GetAllRanks(WCguess.Serv.GetAllRanksRequest request);
        
        // CODEGEN: Generating message contract since element name ID_Usuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRankBy", ReplyAction="*")]
        WCguess.Serv.GetRankByResponse GetRankBy(WCguess.Serv.GetRankByRequest request);
        
        // CODEGEN: Generating message contract since element name ID_Usuario from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsuarioBy", ReplyAction="*")]
        WCguess.Serv.GetUsuarioByResponse GetUsuarioBy(WCguess.Serv.GetUsuarioByRequest request);
        
        // CODEGEN: Generating message contract since element name Guess from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SetGuess", ReplyAction="*")]
        WCguess.Serv.SetGuessResponse SetGuess(WCguess.Serv.SetGuessRequest request);
        
        // CODEGEN: Generating message contract since element name GetGuessResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetGuess", ReplyAction="*")]
        WCguess.Serv.GetGuessResponse GetGuess(WCguess.Serv.GetGuessRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificaLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificaLogin", Namespace="http://tempuri.org/", Order=0)]
        public WCguess.Serv.VerificaLoginRequestBody Body;
        
        public VerificaLoginRequest() {
        }
        
        public VerificaLoginRequest(WCguess.Serv.VerificaLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificaLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string senha;
        
        public VerificaLoginRequestBody() {
        }
        
        public VerificaLoginRequestBody(string email, string senha) {
            this.email = email;
            this.senha = senha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerificaLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerificaLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public WCguess.Serv.VerificaLoginResponseBody Body;
        
        public VerificaLoginResponse() {
        }
        
        public VerificaLoginResponse(WCguess.Serv.VerificaLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerificaLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int VerificaLoginResult;
        
        public VerificaLoginResponseBody() {
        }
        
        public VerificaLoginResponseBody(int VerificaLoginResult) {
            this.VerificaLoginResult = VerificaLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FacebookLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FacebookLogin", Namespace="http://tempuri.org/", Order=0)]
        public WCguess.Serv.FacebookLoginRequestBody Body;
        
        public FacebookLoginRequest() {
        }
        
        public FacebookLoginRequest(WCguess.Serv.FacebookLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FacebookLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lastname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Sexo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Nascimento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Location;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string facebookID;
        
        public FacebookLoginRequestBody() {
        }
        
        public FacebookLoginRequestBody(string name, string lastname, string Sexo, string Nascimento, string Location, string email, string facebookID) {
            this.name = name;
            this.lastname = lastname;
            this.Sexo = Sexo;
            this.Nascimento = Nascimento;
            this.Location = Location;
            this.email = email;
            this.facebookID = facebookID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FacebookLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FacebookLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public WCguess.Serv.FacebookLoginResponseBody Body;
        
        public FacebookLoginResponse() {
        }
        
        public FacebookLoginResponse(WCguess.Serv.FacebookLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FacebookLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int FacebookLoginResult;
        
        public FacebookLoginResponseBody() {
        }
        
        public FacebookLoginResponseBody(int FacebookLoginResult) {
            this.FacebookLoginResult = FacebookLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CadastraLoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CadastraLogin", Namespace="http://tempuri.org/", Order=0)]
        public WCguess.Serv.CadastraLoginRequestBody Body;
        
        public CadastraLoginRequest() {
        }
        
        public CadastraLoginRequest(WCguess.Serv.CadastraLoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CadastraLoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lastname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Sexo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Nascimento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Location;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string senha;
        
        public CadastraLoginRequestBody() {
        }
        
        public CadastraLoginRequestBody(string name, string lastname, string Sexo, string Nascimento, string Location, string email, string senha) {
            this.name = name;
            this.lastname = lastname;
            this.Sexo = Sexo;
            this.Nascimento = Nascimento;
            this.Location = Location;
            this.email = email;
            this.senha = senha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CadastraLoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CadastraLoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public WCguess.Serv.CadastraLoginResponseBody Body;
        
        public CadastraLoginResponse() {
        }
        
        public CadastraLoginResponse(WCguess.Serv.CadastraLoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CadastraLoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CadastraLoginResult;
        
        public CadastraLoginResponseBody() {
        }
        
        public CadastraLoginResponseBody(int CadastraLoginResult) {
            this.CadastraLoginResult = CadastraLoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRanksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllRanks", Namespace="http://tempuri.org/", Order=0)]
        public WCguess.Serv.GetAllRanksRequestBody Body;
        
        public GetAllRanksRequest() {
        }
        
        public GetAllRanksRequest(WCguess.Serv.GetAllRanksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllRanksRequestBody {
        
        public GetAllRanksRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllRanksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllRanksResponse", Namespace="http://tempuri.org/", Order=0)]
        public WCguess.Serv.GetAllRanksResponseBody Body;
        
        public GetAllRanksResponse() {
        }
        
        public GetAllRanksResponse(WCguess.Serv.GetAllRanksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllRanksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WCguess.Serv.ArrayOfString GetAllRanksResult;
        
        public GetAllRanksResponseBody() {
        }
        
        public GetAllRanksResponseBody(WCguess.Serv.ArrayOfString GetAllRanksResult) {
            this.GetAllRanksResult = GetAllRanksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRankByRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRankBy", Namespace="http://tempuri.org/", Order=0)]
        public WCguess.Serv.GetRankByRequestBody Body;
        
        public GetRankByRequest() {
        }
        
        public GetRankByRequest(WCguess.Serv.GetRankByRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRankByRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ID_Usuario;
        
        public GetRankByRequestBody() {
        }
        
        public GetRankByRequestBody(string ID_Usuario) {
            this.ID_Usuario = ID_Usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRankByResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRankByResponse", Namespace="http://tempuri.org/", Order=0)]
        public WCguess.Serv.GetRankByResponseBody Body;
        
        public GetRankByResponse() {
        }
        
        public GetRankByResponse(WCguess.Serv.GetRankByResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRankByResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetRankByResult;
        
        public GetRankByResponseBody() {
        }
        
        public GetRankByResponseBody(string GetRankByResult) {
            this.GetRankByResult = GetRankByResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsuarioByRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsuarioBy", Namespace="http://tempuri.org/", Order=0)]
        public WCguess.Serv.GetUsuarioByRequestBody Body;
        
        public GetUsuarioByRequest() {
        }
        
        public GetUsuarioByRequest(WCguess.Serv.GetUsuarioByRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsuarioByRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ID_Usuario;
        
        public GetUsuarioByRequestBody() {
        }
        
        public GetUsuarioByRequestBody(string ID_Usuario) {
            this.ID_Usuario = ID_Usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUsuarioByResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUsuarioByResponse", Namespace="http://tempuri.org/", Order=0)]
        public WCguess.Serv.GetUsuarioByResponseBody Body;
        
        public GetUsuarioByResponse() {
        }
        
        public GetUsuarioByResponse(WCguess.Serv.GetUsuarioByResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUsuarioByResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUsuarioByResult;
        
        public GetUsuarioByResponseBody() {
        }
        
        public GetUsuarioByResponseBody(string GetUsuarioByResult) {
            this.GetUsuarioByResult = GetUsuarioByResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetGuessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetGuess", Namespace="http://tempuri.org/", Order=0)]
        public WCguess.Serv.SetGuessRequestBody Body;
        
        public SetGuessRequest() {
        }
        
        public SetGuessRequest(WCguess.Serv.SetGuessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetGuessRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Guess;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ID_Usuario;
        
        public SetGuessRequestBody() {
        }
        
        public SetGuessRequestBody(string Guess, string ID_Usuario) {
            this.Guess = Guess;
            this.ID_Usuario = ID_Usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetGuessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetGuessResponse", Namespace="http://tempuri.org/", Order=0)]
        public WCguess.Serv.SetGuessResponseBody Body;
        
        public SetGuessResponse() {
        }
        
        public SetGuessResponse(WCguess.Serv.SetGuessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SetGuessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SetGuessResult;
        
        public SetGuessResponseBody() {
        }
        
        public SetGuessResponseBody(string SetGuessResult) {
            this.SetGuessResult = SetGuessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGuessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGuess", Namespace="http://tempuri.org/", Order=0)]
        public WCguess.Serv.GetGuessRequestBody Body;
        
        public GetGuessRequest() {
        }
        
        public GetGuessRequest(WCguess.Serv.GetGuessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGuessRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ID_Usuario;
        
        public GetGuessRequestBody() {
        }
        
        public GetGuessRequestBody(int ID_Usuario) {
            this.ID_Usuario = ID_Usuario;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGuessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGuessResponse", Namespace="http://tempuri.org/", Order=0)]
        public WCguess.Serv.GetGuessResponseBody Body;
        
        public GetGuessResponse() {
        }
        
        public GetGuessResponse(WCguess.Serv.GetGuessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetGuessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WCguess.Serv.ArrayOfString GetGuessResult;
        
        public GetGuessResponseBody() {
        }
        
        public GetGuessResponseBody(WCguess.Serv.ArrayOfString GetGuessResult) {
            this.GetGuessResult = GetGuessResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HelloGustaSoapChannel : WCguess.Serv.HelloGustaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloGustaSoapClient : System.ServiceModel.ClientBase<WCguess.Serv.HelloGustaSoap>, WCguess.Serv.HelloGustaSoap {
        
        public HelloGustaSoapClient() {
        }
        
        public HelloGustaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloGustaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloGustaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloGustaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCguess.Serv.VerificaLoginResponse WCguess.Serv.HelloGustaSoap.VerificaLogin(WCguess.Serv.VerificaLoginRequest request) {
            return base.Channel.VerificaLogin(request);
        }
        
        public int VerificaLogin(string email, string senha) {
            WCguess.Serv.VerificaLoginRequest inValue = new WCguess.Serv.VerificaLoginRequest();
            inValue.Body = new WCguess.Serv.VerificaLoginRequestBody();
            inValue.Body.email = email;
            inValue.Body.senha = senha;
            WCguess.Serv.VerificaLoginResponse retVal = ((WCguess.Serv.HelloGustaSoap)(this)).VerificaLogin(inValue);
            return retVal.Body.VerificaLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCguess.Serv.FacebookLoginResponse WCguess.Serv.HelloGustaSoap.FacebookLogin(WCguess.Serv.FacebookLoginRequest request) {
            return base.Channel.FacebookLogin(request);
        }
        
        public int FacebookLogin(string name, string lastname, string Sexo, string Nascimento, string Location, string email, string facebookID) {
            WCguess.Serv.FacebookLoginRequest inValue = new WCguess.Serv.FacebookLoginRequest();
            inValue.Body = new WCguess.Serv.FacebookLoginRequestBody();
            inValue.Body.name = name;
            inValue.Body.lastname = lastname;
            inValue.Body.Sexo = Sexo;
            inValue.Body.Nascimento = Nascimento;
            inValue.Body.Location = Location;
            inValue.Body.email = email;
            inValue.Body.facebookID = facebookID;
            WCguess.Serv.FacebookLoginResponse retVal = ((WCguess.Serv.HelloGustaSoap)(this)).FacebookLogin(inValue);
            return retVal.Body.FacebookLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCguess.Serv.CadastraLoginResponse WCguess.Serv.HelloGustaSoap.CadastraLogin(WCguess.Serv.CadastraLoginRequest request) {
            return base.Channel.CadastraLogin(request);
        }
        
        public int CadastraLogin(string name, string lastname, string Sexo, string Nascimento, string Location, string email, string senha) {
            WCguess.Serv.CadastraLoginRequest inValue = new WCguess.Serv.CadastraLoginRequest();
            inValue.Body = new WCguess.Serv.CadastraLoginRequestBody();
            inValue.Body.name = name;
            inValue.Body.lastname = lastname;
            inValue.Body.Sexo = Sexo;
            inValue.Body.Nascimento = Nascimento;
            inValue.Body.Location = Location;
            inValue.Body.email = email;
            inValue.Body.senha = senha;
            WCguess.Serv.CadastraLoginResponse retVal = ((WCguess.Serv.HelloGustaSoap)(this)).CadastraLogin(inValue);
            return retVal.Body.CadastraLoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCguess.Serv.GetAllRanksResponse WCguess.Serv.HelloGustaSoap.GetAllRanks(WCguess.Serv.GetAllRanksRequest request) {
            return base.Channel.GetAllRanks(request);
        }
        
        public WCguess.Serv.ArrayOfString GetAllRanks() {
            WCguess.Serv.GetAllRanksRequest inValue = new WCguess.Serv.GetAllRanksRequest();
            inValue.Body = new WCguess.Serv.GetAllRanksRequestBody();
            WCguess.Serv.GetAllRanksResponse retVal = ((WCguess.Serv.HelloGustaSoap)(this)).GetAllRanks(inValue);
            return retVal.Body.GetAllRanksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCguess.Serv.GetRankByResponse WCguess.Serv.HelloGustaSoap.GetRankBy(WCguess.Serv.GetRankByRequest request) {
            return base.Channel.GetRankBy(request);
        }
        
        public string GetRankBy(string ID_Usuario) {
            WCguess.Serv.GetRankByRequest inValue = new WCguess.Serv.GetRankByRequest();
            inValue.Body = new WCguess.Serv.GetRankByRequestBody();
            inValue.Body.ID_Usuario = ID_Usuario;
            WCguess.Serv.GetRankByResponse retVal = ((WCguess.Serv.HelloGustaSoap)(this)).GetRankBy(inValue);
            return retVal.Body.GetRankByResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCguess.Serv.GetUsuarioByResponse WCguess.Serv.HelloGustaSoap.GetUsuarioBy(WCguess.Serv.GetUsuarioByRequest request) {
            return base.Channel.GetUsuarioBy(request);
        }
        
        public string GetUsuarioBy(string ID_Usuario) {
            WCguess.Serv.GetUsuarioByRequest inValue = new WCguess.Serv.GetUsuarioByRequest();
            inValue.Body = new WCguess.Serv.GetUsuarioByRequestBody();
            inValue.Body.ID_Usuario = ID_Usuario;
            WCguess.Serv.GetUsuarioByResponse retVal = ((WCguess.Serv.HelloGustaSoap)(this)).GetUsuarioBy(inValue);
            return retVal.Body.GetUsuarioByResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCguess.Serv.SetGuessResponse WCguess.Serv.HelloGustaSoap.SetGuess(WCguess.Serv.SetGuessRequest request) {
            return base.Channel.SetGuess(request);
        }
        
        public string SetGuess(string Guess, string ID_Usuario) {
            WCguess.Serv.SetGuessRequest inValue = new WCguess.Serv.SetGuessRequest();
            inValue.Body = new WCguess.Serv.SetGuessRequestBody();
            inValue.Body.Guess = Guess;
            inValue.Body.ID_Usuario = ID_Usuario;
            WCguess.Serv.SetGuessResponse retVal = ((WCguess.Serv.HelloGustaSoap)(this)).SetGuess(inValue);
            return retVal.Body.SetGuessResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WCguess.Serv.GetGuessResponse WCguess.Serv.HelloGustaSoap.GetGuess(WCguess.Serv.GetGuessRequest request) {
            return base.Channel.GetGuess(request);
        }
        
        public WCguess.Serv.ArrayOfString GetGuess(int ID_Usuario) {
            WCguess.Serv.GetGuessRequest inValue = new WCguess.Serv.GetGuessRequest();
            inValue.Body = new WCguess.Serv.GetGuessRequestBody();
            inValue.Body.ID_Usuario = ID_Usuario;
            WCguess.Serv.GetGuessResponse retVal = ((WCguess.Serv.HelloGustaSoap)(this)).GetGuess(inValue);
            return retVal.Body.GetGuessResult;
        }
    }
}
